"""Generate startup chime as raw 16-bit PCM C array (16kHz mono)."""
import math
import struct
import sys
import os

SAMPLE_RATE = 16000
OUTPUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'main', 'startup_chime.h')

# Simple two-tone chime: 800Hz 150ms + silence 30ms + 1200Hz 150ms
def generate_chime():
    samples = []

    # Tone 1: 800Hz, 150ms
    dur = int(0.150 * SAMPLE_RATE)
    for i in range(dur):
        t = i / SAMPLE_RATE
        # Envelope: linear fade in/out
        env = min(i / (SAMPLE_RATE * 0.005), 1.0)  # 5ms attack
        # 10ms release — clamp to [0, 1]
        release = max(min((dur - i) / (SAMPLE_RATE * 0.01), 1.0), 0.0)
        env *= release
        val = int(env * 0.6 * 32767 * math.sin(2 * math.pi * 800 * t))
        samples.append(val)

    # Silence: 30ms
    dur = int(0.030 * SAMPLE_RATE)
    samples.extend([0] * dur)

    # Tone 2: 1200Hz, 150ms
    dur = int(0.150 * SAMPLE_RATE)
    for i in range(dur):
        t = i / SAMPLE_RATE
        env = min(i / (SAMPLE_RATE * 0.005), 1.0)
        env *= max(min((dur - i) / (SAMPLE_RATE * 0.01), 1.0), 0.0)  # 10ms release
        val = int(env * 0.6 * 32767 * math.sin(2 * math.pi * 1200 * t))
        samples.append(val)

    return samples

samples = generate_chime()
total_dur = len(samples) / SAMPLE_RATE

lines = []
lines.append("// Auto-generated startup chime — %d samples (%.2fs) at %d Hz mono 16-bit" % (len(samples), total_dur, SAMPLE_RATE))
lines.append("// Generated by scripts/generate_startup_chime.py")
lines.append("#ifndef STARTUP_CHIME_H_")
lines.append("#define STARTUP_CHIME_H_")
lines.append("#include <stdint.h>")
lines.append("")
lines.append("#define STARTUP_CHIME_SAMPLE_RATE %d" % SAMPLE_RATE)
lines.append("#define STARTUP_CHIME_NUM_SAMPLES %d" % len(samples))
lines.append("")
lines.append("static const int16_t startup_chime_pcm[%d] = {" % len(samples))

for i in range(0, len(samples), 8):
    chunk = samples[i:i+8]
    vals = ", ".join("%6d" % v for v in chunk)
    lines.append("    " + vals + ",")

lines.append("};")
lines.append("")
lines.append("#endif")

with open(OUTPUT, 'w') as f:
    f.write("\n".join(lines) + "\n")

print(f"Generated {len(samples)} samples ({total_dur:.2f}s) -> {OUTPUT}")
