/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "mqtt_agent.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MQTT_AGENT_AGENT_REQUEST, mqtt_agent_agent_request_t, AUTO)


PB_BIND(MQTT_AGENT_AGENT_RESPONSE, mqtt_agent_agent_response_t, AUTO)


PB_BIND(MQTT_AGENT_AUDIO_STATS, mqtt_agent_audio_stats_t, AUTO)


PB_BIND(MQTT_AGENT_AUDIO_FRAME, mqtt_agent_audio_frame_t, AUTO)


PB_BIND(MQTT_AGENT_APP_MSG, mqtt_agent_app_msg_t, AUTO)


PB_BIND(MQTT_AGENT_CHIP_RESPONSE, mqtt_agent_chip_response_t, AUTO)


PB_BIND(MQTT_AGENT_CHIP, mqtt_agent_chip_t, AUTO)


PB_BIND(MQTT_AGENT_CHIP_GROUP, mqtt_agent_chip_group_t, AUTO)


PB_BIND(MQTT_AGENT_CARD, mqtt_agent_card_t, AUTO)


PB_BIND(MQTT_AGENT_AGENT_MSG, mqtt_agent_agent_msg_t, AUTO)







