/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_MQTT_AGENT_MQTT_AGENT_PB_H_INCLUDED
#define PB_MQTT_AGENT_MQTT_AGENT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum mqtt_agent_agent_action {
    MQTT_AGENT_AGENT_ACTION_AGENT_ACTION_UNSPECIFIED = 0,
    MQTT_AGENT_AGENT_ACTION_AGENT_ACTION_CHAT = 1,
    MQTT_AGENT_AGENT_ACTION_AGENT_ACTION_STOP = 2,
    MQTT_AGENT_AGENT_ACTION_AGENT_ACTION_INTERRUPT = 3
} mqtt_agent_agent_action_t;

/* ── downlink: {prefix}/{user_id}/{device_id}/down/agent_response ─────────────
             {prefix}/{user_id}/down/agent_response (App channel) */
typedef enum mqtt_agent_agent_response_code {
    MQTT_AGENT_AGENT_RESPONSE_CODE_AGENT_RESPONSE_CODE_UNSPECIFIED = 0,
    MQTT_AGENT_AGENT_RESPONSE_CODE_AGENT_RESPONSE_CODE_OK = 1, /* session established */
    MQTT_AGENT_AGENT_RESPONSE_CODE_AGENT_RESPONSE_CODE_QUIT = 2, /* session ended: timeout or explicit STOP */
    MQTT_AGENT_AGENT_RESPONSE_CODE_AGENT_RESPONSE_CODE_NO_REQUEST = 3, /* data received without prior CHAT request */
    MQTT_AGENT_AGENT_RESPONSE_CODE_AGENT_RESPONSE_CODE_ERROR = 4 /* rejected (e.g. device not found, internal error) */
} mqtt_agent_agent_response_code_t;

typedef enum mqtt_agent_agent_state {
    MQTT_AGENT_AGENT_STATE_AGENT_STATE_IDLE = 0,
    MQTT_AGENT_AGENT_STATE_AGENT_STATE_THINKING = 1,
    MQTT_AGENT_AGENT_STATE_AGENT_STATE_SPEAKING = 2,
    MQTT_AGENT_AGENT_STATE_AGENT_STATE_WAITING_INPUT = 3
} mqtt_agent_agent_state_t;

/* Struct definitions */
/* ── uplink: {prefix}/{user_id}/{device_id}/up/agent_request ──────────────────
 Session control only; voice travels via up/opus, App text via {user_id}/up/agent_msg */
typedef struct mqtt_agent_agent_request {
    mqtt_agent_agent_action_t action;
    pb_callback_t chat_id; /* optional, echoed back in AgentResponse */
} mqtt_agent_agent_request_t;

typedef struct mqtt_agent_agent_response {
    mqtt_agent_agent_response_code_t code;
    pb_callback_t reason; /* human-readable detail, optional */
} mqtt_agent_agent_response_t;

/* ── Device uplink: {prefix}/{user_id}/{device_id}/up/opus ───────────────────────
 ── Device downlink: {prefix}/{user_id}/{device_id}/down/opus ─────────────────────── */
typedef struct mqtt_agent_audio_stats {
    pb_callback_t transcript; /* STT result */
    pb_callback_t llm_response; /* LLM text (streaming) */
    pb_callback_t extra;
    bool tool_calling; /* LLM executing tool; client shows loading */
} mqtt_agent_audio_stats_t;

typedef struct mqtt_agent_audio_frame {
    uint64_t seq;
    uint64_t timestamp_ms;
    pb_callback_t opus_data;
    bool is_eos; /* TTS done or interrupted */
    bool has_stats;
    mqtt_agent_audio_stats_t stats;
} mqtt_agent_audio_frame_t;

typedef struct mqtt_agent_choice_response {
    pb_callback_t group_id;
    pb_callback_t label;
    pb_callback_t question;
} mqtt_agent_choice_response_t;

/* ── App uplink: {prefix}/{user_id}/up/agent_msg ─────────────────────────── */
typedef struct mqtt_agent_app_msg {
    pb_size_t which_input;
    union {
        pb_callback_t text; /* free-text input */
        mqtt_agent_choice_response_t choice; /* choice selection */
    } input;
} mqtt_agent_app_msg_t;

/* ── App downlink: {prefix}/{user_id}/down/agent_msg ─────────────────────── */
typedef struct mqtt_agent_choice {
    pb_callback_t label;
    pb_callback_t description;
    pb_callback_t payload;
} mqtt_agent_choice_t;

typedef struct mqtt_agent_choice_group {
    pb_callback_t group_id;
    pb_callback_t question;
    bool multi_select;
    pb_callback_t choices;
} mqtt_agent_choice_group_t;

typedef struct mqtt_agent_multi_choice_group {
    pb_callback_t choice_groups;
} mqtt_agent_multi_choice_group_t;

typedef struct mqtt_agent_alert_msg {
    pb_callback_t text;
    pb_callback_t alert_id;
    pb_callback_t task_id; /* task that triggered this alert (empty if not task-driven) */
} mqtt_agent_alert_msg_t;

typedef struct mqtt_agent_hint {
    pb_callback_t label; /* button text, 1-4 chars */
    pb_callback_t text; /* sent as AppMsg(text=...) when tapped */
} mqtt_agent_hint_t;

typedef struct mqtt_agent_agent_text {
    pb_callback_t text;
    pb_callback_t hints;
} mqtt_agent_agent_text_t;

typedef struct mqtt_agent_agent_msg {
    uint64_t seq_id;
    mqtt_agent_agent_state_t state;
    pb_size_t which_agent;
    union {
        mqtt_agent_agent_text_t chat;
        mqtt_agent_multi_choice_group_t choices;
        mqtt_agent_alert_msg_t alert;
    } agent;
} mqtt_agent_agent_msg_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _MQTT_AGENT_AGENT_ACTION_MIN MQTT_AGENT_AGENT_ACTION_AGENT_ACTION_UNSPECIFIED
#define _MQTT_AGENT_AGENT_ACTION_MAX MQTT_AGENT_AGENT_ACTION_AGENT_ACTION_INTERRUPT
#define _MQTT_AGENT_AGENT_ACTION_ARRAYSIZE ((mqtt_agent_agent_action_t)(MQTT_AGENT_AGENT_ACTION_AGENT_ACTION_INTERRUPT+1))

#define _MQTT_AGENT_AGENT_RESPONSE_CODE_MIN MQTT_AGENT_AGENT_RESPONSE_CODE_AGENT_RESPONSE_CODE_UNSPECIFIED
#define _MQTT_AGENT_AGENT_RESPONSE_CODE_MAX MQTT_AGENT_AGENT_RESPONSE_CODE_AGENT_RESPONSE_CODE_ERROR
#define _MQTT_AGENT_AGENT_RESPONSE_CODE_ARRAYSIZE ((mqtt_agent_agent_response_code_t)(MQTT_AGENT_AGENT_RESPONSE_CODE_AGENT_RESPONSE_CODE_ERROR+1))

#define _MQTT_AGENT_AGENT_STATE_MIN MQTT_AGENT_AGENT_STATE_AGENT_STATE_IDLE
#define _MQTT_AGENT_AGENT_STATE_MAX MQTT_AGENT_AGENT_STATE_AGENT_STATE_WAITING_INPUT
#define _MQTT_AGENT_AGENT_STATE_ARRAYSIZE ((mqtt_agent_agent_state_t)(MQTT_AGENT_AGENT_STATE_AGENT_STATE_WAITING_INPUT+1))

#define mqtt_agent_agent_request_t_action_ENUMTYPE mqtt_agent_agent_action_t

#define mqtt_agent_agent_response_t_code_ENUMTYPE mqtt_agent_agent_response_code_t











#define mqtt_agent_agent_msg_t_state_ENUMTYPE mqtt_agent_agent_state_t


/* Initializer values for message structs */
#define MQTT_AGENT_AGENT_REQUEST_INIT_DEFAULT    {_MQTT_AGENT_AGENT_ACTION_MIN, {{NULL}, NULL}}
#define MQTT_AGENT_AGENT_RESPONSE_INIT_DEFAULT   {_MQTT_AGENT_AGENT_RESPONSE_CODE_MIN, {{NULL}, NULL}}
#define MQTT_AGENT_AUDIO_STATS_INIT_DEFAULT      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define MQTT_AGENT_AUDIO_FRAME_INIT_DEFAULT      {0, 0, {{NULL}, NULL}, 0, false, MQTT_AGENT_AUDIO_STATS_INIT_DEFAULT}
#define MQTT_AGENT_APP_MSG_INIT_DEFAULT          {0, {{{NULL}, NULL}}}
#define MQTT_AGENT_CHOICE_RESPONSE_INIT_DEFAULT  {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define MQTT_AGENT_CHOICE_INIT_DEFAULT           {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define MQTT_AGENT_CHOICE_GROUP_INIT_DEFAULT     {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define MQTT_AGENT_MULTI_CHOICE_GROUP_INIT_DEFAULT {{{NULL}, NULL}}
#define MQTT_AGENT_ALERT_MSG_INIT_DEFAULT        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define MQTT_AGENT_HINT_INIT_DEFAULT             {{{NULL}, NULL}, {{NULL}, NULL}}
#define MQTT_AGENT_AGENT_TEXT_INIT_DEFAULT       {{{NULL}, NULL}, {{NULL}, NULL}}
#define MQTT_AGENT_AGENT_MSG_INIT_DEFAULT        {0, _MQTT_AGENT_AGENT_STATE_MIN, 0, {MQTT_AGENT_AGENT_TEXT_INIT_DEFAULT}}
#define MQTT_AGENT_AGENT_REQUEST_INIT_ZERO       {_MQTT_AGENT_AGENT_ACTION_MIN, {{NULL}, NULL}}
#define MQTT_AGENT_AGENT_RESPONSE_INIT_ZERO      {_MQTT_AGENT_AGENT_RESPONSE_CODE_MIN, {{NULL}, NULL}}
#define MQTT_AGENT_AUDIO_STATS_INIT_ZERO         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define MQTT_AGENT_AUDIO_FRAME_INIT_ZERO         {0, 0, {{NULL}, NULL}, 0, false, MQTT_AGENT_AUDIO_STATS_INIT_ZERO}
#define MQTT_AGENT_APP_MSG_INIT_ZERO             {0, {{{NULL}, NULL}}}
#define MQTT_AGENT_CHOICE_RESPONSE_INIT_ZERO     {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define MQTT_AGENT_CHOICE_INIT_ZERO              {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define MQTT_AGENT_CHOICE_GROUP_INIT_ZERO        {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define MQTT_AGENT_MULTI_CHOICE_GROUP_INIT_ZERO  {{{NULL}, NULL}}
#define MQTT_AGENT_ALERT_MSG_INIT_ZERO           {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define MQTT_AGENT_HINT_INIT_ZERO                {{{NULL}, NULL}, {{NULL}, NULL}}
#define MQTT_AGENT_AGENT_TEXT_INIT_ZERO          {{{NULL}, NULL}, {{NULL}, NULL}}
#define MQTT_AGENT_AGENT_MSG_INIT_ZERO           {0, _MQTT_AGENT_AGENT_STATE_MIN, 0, {MQTT_AGENT_AGENT_TEXT_INIT_ZERO}}

/* Field tags (for use in manual encoding/decoding) */
#define MQTT_AGENT_AGENT_REQUEST_ACTION_TAG      1
#define MQTT_AGENT_AGENT_REQUEST_CHAT_ID_TAG     2
#define MQTT_AGENT_AGENT_RESPONSE_CODE_TAG       1
#define MQTT_AGENT_AGENT_RESPONSE_REASON_TAG     2
#define MQTT_AGENT_AUDIO_STATS_TRANSCRIPT_TAG    1
#define MQTT_AGENT_AUDIO_STATS_LLM_RESPONSE_TAG  2
#define MQTT_AGENT_AUDIO_STATS_EXTRA_TAG         3
#define MQTT_AGENT_AUDIO_STATS_TOOL_CALLING_TAG  4
#define MQTT_AGENT_AUDIO_FRAME_SEQ_TAG           1
#define MQTT_AGENT_AUDIO_FRAME_TIMESTAMP_MS_TAG  2
#define MQTT_AGENT_AUDIO_FRAME_OPUS_DATA_TAG     3
#define MQTT_AGENT_AUDIO_FRAME_IS_EOS_TAG        4
#define MQTT_AGENT_AUDIO_FRAME_STATS_TAG         5
#define MQTT_AGENT_CHOICE_RESPONSE_GROUP_ID_TAG  1
#define MQTT_AGENT_CHOICE_RESPONSE_LABEL_TAG     2
#define MQTT_AGENT_CHOICE_RESPONSE_QUESTION_TAG  3
#define MQTT_AGENT_APP_MSG_TEXT_TAG              1
#define MQTT_AGENT_APP_MSG_CHOICE_TAG            2
#define MQTT_AGENT_CHOICE_LABEL_TAG              1
#define MQTT_AGENT_CHOICE_DESCRIPTION_TAG        2
#define MQTT_AGENT_CHOICE_PAYLOAD_TAG            3
#define MQTT_AGENT_CHOICE_GROUP_GROUP_ID_TAG     1
#define MQTT_AGENT_CHOICE_GROUP_QUESTION_TAG     2
#define MQTT_AGENT_CHOICE_GROUP_MULTI_SELECT_TAG 3
#define MQTT_AGENT_CHOICE_GROUP_CHOICES_TAG      4
#define MQTT_AGENT_MULTI_CHOICE_GROUP_CHOICE_GROUPS_TAG 1
#define MQTT_AGENT_ALERT_MSG_TEXT_TAG            1
#define MQTT_AGENT_ALERT_MSG_ALERT_ID_TAG        2
#define MQTT_AGENT_ALERT_MSG_TASK_ID_TAG         3
#define MQTT_AGENT_HINT_LABEL_TAG                1
#define MQTT_AGENT_HINT_TEXT_TAG                 2
#define MQTT_AGENT_AGENT_TEXT_TEXT_TAG           1
#define MQTT_AGENT_AGENT_TEXT_HINTS_TAG          2
#define MQTT_AGENT_AGENT_MSG_SEQ_ID_TAG          1
#define MQTT_AGENT_AGENT_MSG_STATE_TAG           3
#define MQTT_AGENT_AGENT_MSG_CHAT_TAG            4
#define MQTT_AGENT_AGENT_MSG_CHOICES_TAG         5
#define MQTT_AGENT_AGENT_MSG_ALERT_TAG           6

/* Struct field encoding specification for nanopb */
#define MQTT_AGENT_AGENT_REQUEST_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    action,            1) \
X(a, CALLBACK, SINGULAR, STRING,   chat_id,           2)
#define MQTT_AGENT_AGENT_REQUEST_CALLBACK pb_default_field_callback
#define MQTT_AGENT_AGENT_REQUEST_DEFAULT NULL

#define MQTT_AGENT_AGENT_RESPONSE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    code,              1) \
X(a, CALLBACK, SINGULAR, STRING,   reason,            2)
#define MQTT_AGENT_AGENT_RESPONSE_CALLBACK pb_default_field_callback
#define MQTT_AGENT_AGENT_RESPONSE_DEFAULT NULL

#define MQTT_AGENT_AUDIO_STATS_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   transcript,        1) \
X(a, CALLBACK, SINGULAR, STRING,   llm_response,      2) \
X(a, CALLBACK, SINGULAR, STRING,   extra,             3) \
X(a, STATIC,   SINGULAR, BOOL,     tool_calling,      4)
#define MQTT_AGENT_AUDIO_STATS_CALLBACK pb_default_field_callback
#define MQTT_AGENT_AUDIO_STATS_DEFAULT NULL

#define MQTT_AGENT_AUDIO_FRAME_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   seq,               1) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_ms,      2) \
X(a, CALLBACK, SINGULAR, BYTES,    opus_data,         3) \
X(a, STATIC,   SINGULAR, BOOL,     is_eos,            4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  stats,             5)
#define MQTT_AGENT_AUDIO_FRAME_CALLBACK pb_default_field_callback
#define MQTT_AGENT_AUDIO_FRAME_DEFAULT NULL
#define mqtt_agent_audio_frame_t_stats_MSGTYPE mqtt_agent_audio_stats_t

#define MQTT_AGENT_APP_MSG_FIELDLIST(X, a) \
X(a, CALLBACK, ONEOF,    STRING,   (input,text,input.text),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (input,choice,input.choice),   2)
#define MQTT_AGENT_APP_MSG_CALLBACK pb_default_field_callback
#define MQTT_AGENT_APP_MSG_DEFAULT NULL
#define mqtt_agent_app_msg_t_input_choice_MSGTYPE mqtt_agent_choice_response_t

#define MQTT_AGENT_CHOICE_RESPONSE_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   group_id,          1) \
X(a, CALLBACK, SINGULAR, STRING,   label,             2) \
X(a, CALLBACK, SINGULAR, STRING,   question,          3)
#define MQTT_AGENT_CHOICE_RESPONSE_CALLBACK pb_default_field_callback
#define MQTT_AGENT_CHOICE_RESPONSE_DEFAULT NULL

#define MQTT_AGENT_CHOICE_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   label,             1) \
X(a, CALLBACK, SINGULAR, STRING,   description,       2) \
X(a, CALLBACK, SINGULAR, STRING,   payload,           3)
#define MQTT_AGENT_CHOICE_CALLBACK pb_default_field_callback
#define MQTT_AGENT_CHOICE_DEFAULT NULL

#define MQTT_AGENT_CHOICE_GROUP_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   group_id,          1) \
X(a, CALLBACK, SINGULAR, STRING,   question,          2) \
X(a, STATIC,   SINGULAR, BOOL,     multi_select,      3) \
X(a, CALLBACK, REPEATED, MESSAGE,  choices,           4)
#define MQTT_AGENT_CHOICE_GROUP_CALLBACK pb_default_field_callback
#define MQTT_AGENT_CHOICE_GROUP_DEFAULT NULL
#define mqtt_agent_choice_group_t_choices_MSGTYPE mqtt_agent_choice_t

#define MQTT_AGENT_MULTI_CHOICE_GROUP_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  choice_groups,     1)
#define MQTT_AGENT_MULTI_CHOICE_GROUP_CALLBACK pb_default_field_callback
#define MQTT_AGENT_MULTI_CHOICE_GROUP_DEFAULT NULL
#define mqtt_agent_multi_choice_group_t_choice_groups_MSGTYPE mqtt_agent_choice_group_t

#define MQTT_AGENT_ALERT_MSG_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   text,              1) \
X(a, CALLBACK, SINGULAR, STRING,   alert_id,          2) \
X(a, CALLBACK, SINGULAR, STRING,   task_id,           3)
#define MQTT_AGENT_ALERT_MSG_CALLBACK pb_default_field_callback
#define MQTT_AGENT_ALERT_MSG_DEFAULT NULL

#define MQTT_AGENT_HINT_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   label,             1) \
X(a, CALLBACK, SINGULAR, STRING,   text,              2)
#define MQTT_AGENT_HINT_CALLBACK pb_default_field_callback
#define MQTT_AGENT_HINT_DEFAULT NULL

#define MQTT_AGENT_AGENT_TEXT_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   text,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  hints,             2)
#define MQTT_AGENT_AGENT_TEXT_CALLBACK pb_default_field_callback
#define MQTT_AGENT_AGENT_TEXT_DEFAULT NULL
#define mqtt_agent_agent_text_t_hints_MSGTYPE mqtt_agent_hint_t

#define MQTT_AGENT_AGENT_MSG_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   seq_id,            1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (agent,chat,agent.chat),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (agent,choices,agent.choices),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (agent,alert,agent.alert),   6)
#define MQTT_AGENT_AGENT_MSG_CALLBACK NULL
#define MQTT_AGENT_AGENT_MSG_DEFAULT NULL
#define mqtt_agent_agent_msg_t_agent_chat_MSGTYPE mqtt_agent_agent_text_t
#define mqtt_agent_agent_msg_t_agent_choices_MSGTYPE mqtt_agent_multi_choice_group_t
#define mqtt_agent_agent_msg_t_agent_alert_MSGTYPE mqtt_agent_alert_msg_t

extern const pb_msgdesc_t mqtt_agent_agent_request_t_msg;
extern const pb_msgdesc_t mqtt_agent_agent_response_t_msg;
extern const pb_msgdesc_t mqtt_agent_audio_stats_t_msg;
extern const pb_msgdesc_t mqtt_agent_audio_frame_t_msg;
extern const pb_msgdesc_t mqtt_agent_app_msg_t_msg;
extern const pb_msgdesc_t mqtt_agent_choice_response_t_msg;
extern const pb_msgdesc_t mqtt_agent_choice_t_msg;
extern const pb_msgdesc_t mqtt_agent_choice_group_t_msg;
extern const pb_msgdesc_t mqtt_agent_multi_choice_group_t_msg;
extern const pb_msgdesc_t mqtt_agent_alert_msg_t_msg;
extern const pb_msgdesc_t mqtt_agent_hint_t_msg;
extern const pb_msgdesc_t mqtt_agent_agent_text_t_msg;
extern const pb_msgdesc_t mqtt_agent_agent_msg_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MQTT_AGENT_AGENT_REQUEST_FIELDS &mqtt_agent_agent_request_t_msg
#define MQTT_AGENT_AGENT_RESPONSE_FIELDS &mqtt_agent_agent_response_t_msg
#define MQTT_AGENT_AUDIO_STATS_FIELDS &mqtt_agent_audio_stats_t_msg
#define MQTT_AGENT_AUDIO_FRAME_FIELDS &mqtt_agent_audio_frame_t_msg
#define MQTT_AGENT_APP_MSG_FIELDS &mqtt_agent_app_msg_t_msg
#define MQTT_AGENT_CHOICE_RESPONSE_FIELDS &mqtt_agent_choice_response_t_msg
#define MQTT_AGENT_CHOICE_FIELDS &mqtt_agent_choice_t_msg
#define MQTT_AGENT_CHOICE_GROUP_FIELDS &mqtt_agent_choice_group_t_msg
#define MQTT_AGENT_MULTI_CHOICE_GROUP_FIELDS &mqtt_agent_multi_choice_group_t_msg
#define MQTT_AGENT_ALERT_MSG_FIELDS &mqtt_agent_alert_msg_t_msg
#define MQTT_AGENT_HINT_FIELDS &mqtt_agent_hint_t_msg
#define MQTT_AGENT_AGENT_TEXT_FIELDS &mqtt_agent_agent_text_t_msg
#define MQTT_AGENT_AGENT_MSG_FIELDS &mqtt_agent_agent_msg_t_msg

/* Maximum encoded size of messages (where known) */
/* mqtt_agent_AgentRequest_size depends on runtime parameters */
/* mqtt_agent_AgentResponse_size depends on runtime parameters */
/* mqtt_agent_AudioStats_size depends on runtime parameters */
/* mqtt_agent_AudioFrame_size depends on runtime parameters */
/* mqtt_agent_AppMsg_size depends on runtime parameters */
/* mqtt_agent_ChoiceResponse_size depends on runtime parameters */
/* mqtt_agent_Choice_size depends on runtime parameters */
/* mqtt_agent_ChoiceGroup_size depends on runtime parameters */
/* mqtt_agent_MultiChoiceGroup_size depends on runtime parameters */
/* mqtt_agent_AlertMsg_size depends on runtime parameters */
/* mqtt_agent_Hint_size depends on runtime parameters */
/* mqtt_agent_AgentText_size depends on runtime parameters */
/* mqtt_agent_AgentMsg_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
