/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_MQTT_AGENT_MQTT_AGENT_PB_H_INCLUDED
#define PB_MQTT_AGENT_MQTT_AGENT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum mqtt_agent_agent_action {
    MQTT_AGENT_AGENT_ACTION_AGENT_ACTION_UNSPECIFIED = 0,
    MQTT_AGENT_AGENT_ACTION_AGENT_ACTION_CHAT = 1,
    MQTT_AGENT_AGENT_ACTION_AGENT_ACTION_STOP = 2,
    MQTT_AGENT_AGENT_ACTION_AGENT_ACTION_INTERRUPT = 3 /* 打断当前 TTS 播放 */
} mqtt_agent_agent_action_t;

/* Struct definitions */
typedef struct mqtt_agent_agent_request {
    mqtt_agent_agent_action_t action;
    pb_callback_t chat_id; /* optional, Agent Server 生成后回传 */
} mqtt_agent_agent_request_t;

typedef struct mqtt_agent_audio_stats {
    pb_callback_t transcript; /* STT 识别文本，识别完成后下发 */
    pb_callback_t llm_response; /* LLM 回复文本，LLM 返回后下发（不含 tool_calls） */
    pb_callback_t extra;
} mqtt_agent_audio_stats_t;

typedef struct mqtt_agent_audio_frame {
    uint64_t seq;
    uint64_t timestamp_ms;
    pb_callback_t opus_data;
    bool is_eos; /* End of Stream: TTS 播放完毕或被打断时设为 true */
    bool has_stats;
    mqtt_agent_audio_stats_t stats;
} mqtt_agent_audio_frame_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _MQTT_AGENT_AGENT_ACTION_MIN MQTT_AGENT_AGENT_ACTION_AGENT_ACTION_UNSPECIFIED
#define _MQTT_AGENT_AGENT_ACTION_MAX MQTT_AGENT_AGENT_ACTION_AGENT_ACTION_INTERRUPT
#define _MQTT_AGENT_AGENT_ACTION_ARRAYSIZE ((mqtt_agent_agent_action_t)(MQTT_AGENT_AGENT_ACTION_AGENT_ACTION_INTERRUPT+1))

#define mqtt_agent_agent_request_t_action_ENUMTYPE mqtt_agent_agent_action_t




/* Initializer values for message structs */
#define MQTT_AGENT_AGENT_REQUEST_INIT_DEFAULT    {_MQTT_AGENT_AGENT_ACTION_MIN, {{NULL}, NULL}}
#define MQTT_AGENT_AUDIO_STATS_INIT_DEFAULT      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define MQTT_AGENT_AUDIO_FRAME_INIT_DEFAULT      {0, 0, {{NULL}, NULL}, 0, false, MQTT_AGENT_AUDIO_STATS_INIT_DEFAULT}
#define MQTT_AGENT_AGENT_REQUEST_INIT_ZERO       {_MQTT_AGENT_AGENT_ACTION_MIN, {{NULL}, NULL}}
#define MQTT_AGENT_AUDIO_STATS_INIT_ZERO         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define MQTT_AGENT_AUDIO_FRAME_INIT_ZERO         {0, 0, {{NULL}, NULL}, 0, false, MQTT_AGENT_AUDIO_STATS_INIT_ZERO}

/* Field tags (for use in manual encoding/decoding) */
#define MQTT_AGENT_AGENT_REQUEST_ACTION_TAG      1
#define MQTT_AGENT_AGENT_REQUEST_CHAT_ID_TAG     2
#define MQTT_AGENT_AUDIO_STATS_TRANSCRIPT_TAG    1
#define MQTT_AGENT_AUDIO_STATS_LLM_RESPONSE_TAG  2
#define MQTT_AGENT_AUDIO_STATS_EXTRA_TAG         3
#define MQTT_AGENT_AUDIO_FRAME_SEQ_TAG           1
#define MQTT_AGENT_AUDIO_FRAME_TIMESTAMP_MS_TAG  2
#define MQTT_AGENT_AUDIO_FRAME_OPUS_DATA_TAG     3
#define MQTT_AGENT_AUDIO_FRAME_IS_EOS_TAG        4
#define MQTT_AGENT_AUDIO_FRAME_STATS_TAG         5

/* Struct field encoding specification for nanopb */
#define MQTT_AGENT_AGENT_REQUEST_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    action,            1) \
X(a, CALLBACK, SINGULAR, STRING,   chat_id,           2)
#define MQTT_AGENT_AGENT_REQUEST_CALLBACK pb_default_field_callback
#define MQTT_AGENT_AGENT_REQUEST_DEFAULT NULL

#define MQTT_AGENT_AUDIO_STATS_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   transcript,        1) \
X(a, CALLBACK, SINGULAR, STRING,   llm_response,      2) \
X(a, CALLBACK, SINGULAR, STRING,   extra,             3)
#define MQTT_AGENT_AUDIO_STATS_CALLBACK pb_default_field_callback
#define MQTT_AGENT_AUDIO_STATS_DEFAULT NULL

#define MQTT_AGENT_AUDIO_FRAME_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   seq,               1) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_ms,      2) \
X(a, CALLBACK, SINGULAR, BYTES,    opus_data,         3) \
X(a, STATIC,   SINGULAR, BOOL,     is_eos,            4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  stats,             5)
#define MQTT_AGENT_AUDIO_FRAME_CALLBACK pb_default_field_callback
#define MQTT_AGENT_AUDIO_FRAME_DEFAULT NULL
#define mqtt_agent_audio_frame_t_stats_MSGTYPE mqtt_agent_audio_stats_t

extern const pb_msgdesc_t mqtt_agent_agent_request_t_msg;
extern const pb_msgdesc_t mqtt_agent_audio_stats_t_msg;
extern const pb_msgdesc_t mqtt_agent_audio_frame_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MQTT_AGENT_AGENT_REQUEST_FIELDS &mqtt_agent_agent_request_t_msg
#define MQTT_AGENT_AUDIO_STATS_FIELDS &mqtt_agent_audio_stats_t_msg
#define MQTT_AGENT_AUDIO_FRAME_FIELDS &mqtt_agent_audio_frame_t_msg

/* Maximum encoded size of messages (where known) */
/* mqtt_agent_AgentRequest_size depends on runtime parameters */
/* mqtt_agent_AudioStats_size depends on runtime parameters */
/* mqtt_agent_AudioFrame_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
