/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "mqtt_agent.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MQTT_AGENT_AGENT_REQUEST, mqtt_agent_agent_request_t, AUTO)


PB_BIND(MQTT_AGENT_AUDIO_STATS, mqtt_agent_audio_stats_t, AUTO)


PB_BIND(MQTT_AGENT_AUDIO_FRAME, mqtt_agent_audio_frame_t, AUTO)





