/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "device.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(DEVICE_VIDEO_MSG, device_video_msg_t, AUTO)


PB_BIND(DEVICE_EVENT_MSG, device_event_msg_t, AUTO)


PB_BIND(DEVICE_STATUS_REPORT, device_status_report_t, AUTO)


PB_BIND(DEVICE_UPLOAD_LOGS, device_upload_logs_t, 2)


PB_BIND(DEVICE_JOIN_ROOM, device_join_room_t, 2)


PB_BIND(DEVICE_LEAVE_ROOM, device_leave_room_t, AUTO)


PB_BIND(DEVICE_QUERY_EVENT, device_query_event_t, AUTO)


PB_BIND(DEVICE_OPEN_LIGHT, device_open_light_t, AUTO)


PB_BIND(DEVICE_CLOSE_LIGHT, device_close_light_t, AUTO)


PB_BIND(DEVICE_TAKE_PHOTO, device_take_photo_t, AUTO)


PB_BIND(DEVICE_REBOOT, device_reboot_t, AUTO)


PB_BIND(DEVICE_RELAY_CONTROL, device_relay_control_t, AUTO)


PB_BIND(DEVICE_COMMAND, device_command_t, 2)


PB_BIND(DEVICE_JOIN_ROOM_RESP, device_join_room_resp_t, AUTO)


PB_BIND(DEVICE_LEAVE_ROOM_RESP, device_leave_room_resp_t, AUTO)


PB_BIND(DEVICE_UPLOAD_LOGS_RESP, device_upload_logs_resp_t, AUTO)


PB_BIND(DEVICE_QUERY_EVENT_RESP, device_query_event_resp_t, 4)


PB_BIND(DEVICE_OPEN_LIGHT_RESP, device_open_light_resp_t, AUTO)


PB_BIND(DEVICE_CLOSE_LIGHT_RESP, device_close_light_resp_t, AUTO)


PB_BIND(DEVICE_TAKE_PHOTO_RESP, device_take_photo_resp_t, AUTO)


PB_BIND(DEVICE_REBOOT_RESP, device_reboot_resp_t, AUTO)


PB_BIND(DEVICE_RELAY_CONTROL_RESP, device_relay_control_resp_t, AUTO)


PB_BIND(DEVICE_COMMAND_RESPONSE, device_command_response_t, 4)


PB_BIND(DEVICE_PTZ_CONTROL, device_ptz_control_t, AUTO)


PB_BIND(DEVICE_CHAT_REQUEST, device_chat_request_t, AUTO)


PB_BIND(DEVICE_CRON_REQUEST, device_cron_request_t, AUTO)


PB_BIND(DEVICE_AGENT_REQUEST, device_agent_request_t, AUTO)


PB_BIND(DEVICE_CHAT_RESPONSE, device_chat_response_t, 2)


PB_BIND(DEVICE_CRON_RESPONSE, device_cron_response_t, AUTO)


PB_BIND(DEVICE_AGENT_RESPONSE, device_agent_response_t, 2)

















