/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_FLOWER_FLOWER_PB_H_INCLUDED
#define PB_FLOWER_FLOWER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum flower_cmd_result {
    FLOWER_CMD_RESULT_OK = 0,
    FLOWER_CMD_RESULT_BUSY = 1
} flower_cmd_result_t;

typedef enum flower_command_role {
    FLOWER_COMMAND_ROLE_COMMAND_ROLE_UNSPECIFIED = 0,
    FLOWER_COMMAND_ROLE_COMMAND_ROLE_BACKEND = 1,
    FLOWER_COMMAND_ROLE_COMMAND_ROLE_APP = 2,
    FLOWER_COMMAND_ROLE_COMMAND_ROLE_AGENT = 3
} flower_command_role_t;

/* Struct definitions */
typedef struct flower_relay_control {
    bool on;
    uint32_t duration_ms; /* auto-off delay (ms); 0 = no auto-off */
} flower_relay_control_t;

typedef struct flower_relay_control_resp {
    flower_cmd_result_t result;
    char reason[64];
} flower_relay_control_resp_t;

/* 下行：指令 */
typedef struct flower_command {
    flower_command_role_t role;
    pb_size_t which_payload;
    union {
        flower_relay_control_t relay_control;
    } payload;
} flower_command_t;

/* 上行：指令结果
 device_id not included — it is conveyed by the MQTT topic */
typedef struct flower_command_response {
    flower_command_role_t role; /* mirrors Command.role */
    pb_size_t which_payload;
    union {
        flower_relay_control_resp_t relay_control;
    } payload;
} flower_command_response_t;

typedef struct flower_device_version {
    int32_t major;
    int32_t minor;
    int32_t patch;
} flower_device_version_t;

typedef struct flower_status_report {
    int32_t signal_dbm; /* ADC/WiFi signal */
    int64_t timestamp; /* device local time (unix ms) */
    bool has_version;
    flower_device_version_t version;
} flower_status_report_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _FLOWER_CMD_RESULT_MIN FLOWER_CMD_RESULT_OK
#define _FLOWER_CMD_RESULT_MAX FLOWER_CMD_RESULT_BUSY
#define _FLOWER_CMD_RESULT_ARRAYSIZE ((flower_cmd_result_t)(FLOWER_CMD_RESULT_BUSY+1))

#define _FLOWER_COMMAND_ROLE_MIN FLOWER_COMMAND_ROLE_COMMAND_ROLE_UNSPECIFIED
#define _FLOWER_COMMAND_ROLE_MAX FLOWER_COMMAND_ROLE_COMMAND_ROLE_AGENT
#define _FLOWER_COMMAND_ROLE_ARRAYSIZE ((flower_command_role_t)(FLOWER_COMMAND_ROLE_COMMAND_ROLE_AGENT+1))



#define flower_relay_control_resp_t_result_ENUMTYPE flower_cmd_result_t

#define flower_command_t_role_ENUMTYPE flower_command_role_t

#define flower_command_response_t_role_ENUMTYPE flower_command_role_t



/* Initializer values for message structs */
#define FLOWER_STATUS_REPORT_INIT_DEFAULT        {0, 0, false, FLOWER_DEVICE_VERSION_INIT_DEFAULT}
#define FLOWER_RELAY_CONTROL_INIT_DEFAULT        {0, 0}
#define FLOWER_RELAY_CONTROL_RESP_INIT_DEFAULT   {_FLOWER_CMD_RESULT_MIN, ""}
#define FLOWER_COMMAND_INIT_DEFAULT              {_FLOWER_COMMAND_ROLE_MIN, 0, {FLOWER_RELAY_CONTROL_INIT_DEFAULT}}
#define FLOWER_COMMAND_RESPONSE_INIT_DEFAULT     {_FLOWER_COMMAND_ROLE_MIN, 0, {FLOWER_RELAY_CONTROL_RESP_INIT_DEFAULT}}
#define FLOWER_DEVICE_VERSION_INIT_DEFAULT       {0, 0, 0}
#define FLOWER_STATUS_REPORT_INIT_ZERO           {0, 0, false, FLOWER_DEVICE_VERSION_INIT_ZERO}
#define FLOWER_RELAY_CONTROL_INIT_ZERO           {0, 0}
#define FLOWER_RELAY_CONTROL_RESP_INIT_ZERO      {_FLOWER_CMD_RESULT_MIN, ""}
#define FLOWER_COMMAND_INIT_ZERO                 {_FLOWER_COMMAND_ROLE_MIN, 0, {FLOWER_RELAY_CONTROL_INIT_ZERO}}
#define FLOWER_COMMAND_RESPONSE_INIT_ZERO        {_FLOWER_COMMAND_ROLE_MIN, 0, {FLOWER_RELAY_CONTROL_RESP_INIT_ZERO}}
#define FLOWER_DEVICE_VERSION_INIT_ZERO          {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define FLOWER_RELAY_CONTROL_ON_TAG              1
#define FLOWER_RELAY_CONTROL_DURATION_MS_TAG     2
#define FLOWER_RELAY_CONTROL_RESP_RESULT_TAG     1
#define FLOWER_RELAY_CONTROL_RESP_REASON_TAG     2
#define FLOWER_COMMAND_ROLE_TAG                  1
#define FLOWER_COMMAND_RELAY_CONTROL_TAG         2
#define FLOWER_COMMAND_RESPONSE_ROLE_TAG         1
#define FLOWER_COMMAND_RESPONSE_RELAY_CONTROL_TAG 2
#define FLOWER_DEVICE_VERSION_MAJOR_TAG          1
#define FLOWER_DEVICE_VERSION_MINOR_TAG          2
#define FLOWER_DEVICE_VERSION_PATCH_TAG          3
#define FLOWER_STATUS_REPORT_SIGNAL_DBM_TAG      1
#define FLOWER_STATUS_REPORT_TIMESTAMP_TAG       2
#define FLOWER_STATUS_REPORT_VERSION_TAG         3

/* Struct field encoding specification for nanopb */
#define FLOWER_STATUS_REPORT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    signal_dbm,        1) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           3)
#define FLOWER_STATUS_REPORT_CALLBACK NULL
#define FLOWER_STATUS_REPORT_DEFAULT NULL
#define flower_status_report_t_version_MSGTYPE flower_device_version_t

#define FLOWER_RELAY_CONTROL_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     on,                1) \
X(a, STATIC,   SINGULAR, UINT32,   duration_ms,       2)
#define FLOWER_RELAY_CONTROL_CALLBACK NULL
#define FLOWER_RELAY_CONTROL_DEFAULT NULL

#define FLOWER_RELAY_CONTROL_RESP_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    result,            1) \
X(a, STATIC,   SINGULAR, STRING,   reason,            2)
#define FLOWER_RELAY_CONTROL_RESP_CALLBACK NULL
#define FLOWER_RELAY_CONTROL_RESP_DEFAULT NULL

#define FLOWER_COMMAND_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    role,              1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,relay_control,payload.relay_control),   2)
#define FLOWER_COMMAND_CALLBACK NULL
#define FLOWER_COMMAND_DEFAULT NULL
#define flower_command_t_payload_relay_control_MSGTYPE flower_relay_control_t

#define FLOWER_COMMAND_RESPONSE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    role,              1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,relay_control,payload.relay_control),   2)
#define FLOWER_COMMAND_RESPONSE_CALLBACK NULL
#define FLOWER_COMMAND_RESPONSE_DEFAULT NULL
#define flower_command_response_t_payload_relay_control_MSGTYPE flower_relay_control_resp_t

#define FLOWER_DEVICE_VERSION_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    major,             1) \
X(a, STATIC,   SINGULAR, INT32,    minor,             2) \
X(a, STATIC,   SINGULAR, INT32,    patch,             3)
#define FLOWER_DEVICE_VERSION_CALLBACK NULL
#define FLOWER_DEVICE_VERSION_DEFAULT NULL

extern const pb_msgdesc_t flower_status_report_t_msg;
extern const pb_msgdesc_t flower_relay_control_t_msg;
extern const pb_msgdesc_t flower_relay_control_resp_t_msg;
extern const pb_msgdesc_t flower_command_t_msg;
extern const pb_msgdesc_t flower_command_response_t_msg;
extern const pb_msgdesc_t flower_device_version_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define FLOWER_STATUS_REPORT_FIELDS &flower_status_report_t_msg
#define FLOWER_RELAY_CONTROL_FIELDS &flower_relay_control_t_msg
#define FLOWER_RELAY_CONTROL_RESP_FIELDS &flower_relay_control_resp_t_msg
#define FLOWER_COMMAND_FIELDS &flower_command_t_msg
#define FLOWER_COMMAND_RESPONSE_FIELDS &flower_command_response_t_msg
#define FLOWER_DEVICE_VERSION_FIELDS &flower_device_version_t_msg

/* Maximum encoded size of messages (where known) */
#define FLOWER_COMMAND_RESPONSE_SIZE             71
#define FLOWER_COMMAND_SIZE                      12
#define FLOWER_DEVICE_VERSION_SIZE               33
#define FLOWER_FLOWER_PB_H_MAX_SIZE              FLOWER_COMMAND_RESPONSE_SIZE
#define FLOWER_RELAY_CONTROL_RESP_SIZE           67
#define FLOWER_RELAY_CONTROL_SIZE                8
#define FLOWER_STATUS_REPORT_SIZE                57

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
