/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_FLOWER_FLOWER_PB_H_INCLUDED
#define PB_FLOWER_FLOWER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum flower_cmd_result {
    FLOWER_CMD_RESULT_OK = 0,
    FLOWER_CMD_RESULT_BUSY = 1
} flower_cmd_result_t;

typedef enum flower_ota_status {
    FLOWER_OTA_STATUS_OTA_STARTED = 0,
    FLOWER_OTA_STATUS_OTA_PROGRESS = 1,
    FLOWER_OTA_STATUS_OTA_SUCCESS = 2,
    FLOWER_OTA_STATUS_OTA_FAILED = 3
} flower_ota_status_t;

typedef enum flower_command_role {
    FLOWER_COMMAND_ROLE_COMMAND_ROLE_UNSPECIFIED = 0,
    FLOWER_COMMAND_ROLE_COMMAND_ROLE_BACKEND = 1,
    FLOWER_COMMAND_ROLE_COMMAND_ROLE_APP = 2,
    FLOWER_COMMAND_ROLE_COMMAND_ROLE_AGENT = 3
} flower_command_role_t;

/* Struct definitions */
typedef struct flower_relay_control {
    bool on;
    uint32_t duration_ms; /* auto-off delay (ms); 0 = no auto-off */
} flower_relay_control_t;

typedef struct flower_ota_response {
    flower_ota_status_t status;
    int32_t progress; /* 0-100, valid when status == OTA_PROGRESS */
    char message[32]; /* error detail on OTA_FAILED */
} flower_ota_response_t;

typedef struct flower_relay_control_resp {
    flower_cmd_result_t result;
    char reason[64];
} flower_relay_control_resp_t;

/* 上行：指令结果
 device_id not included — it is conveyed by the MQTT topic */
typedef struct flower_command_response {
    flower_command_role_t role; /* mirrors Command.role */
    pb_size_t which_payload;
    union {
        flower_relay_control_resp_t relay_control;
        flower_ota_response_t ota;
    } payload;
} flower_command_response_t;

typedef struct flower_device_version {
    int32_t major;
    int32_t minor;
    int32_t patch;
} flower_device_version_t;

typedef struct flower_status_report {
    int32_t signal_dbm; /* ADC/WiFi signal */
    int64_t timestamp; /* device local time (unix ms) */
    bool has_version;
    flower_device_version_t version;
} flower_status_report_t;

typedef struct flower_ota_command {
    char url[256]; /* HTTPS URL of the firmware binary */
    bool has_expected_version;
    flower_device_version_t expected_version; /* expected version */
    bool has_mini_compact_version;
    flower_device_version_t mini_compact_version; /* compact version */
} flower_ota_command_t;

/* 下行：指令 */
typedef struct flower_command {
    flower_command_role_t role;
    pb_size_t which_payload;
    union {
        flower_relay_control_t relay_control;
        flower_ota_command_t ota;
    } payload;
} flower_command_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _FLOWER_CMD_RESULT_MIN FLOWER_CMD_RESULT_OK
#define _FLOWER_CMD_RESULT_MAX FLOWER_CMD_RESULT_BUSY
#define _FLOWER_CMD_RESULT_ARRAYSIZE ((flower_cmd_result_t)(FLOWER_CMD_RESULT_BUSY+1))

#define _FLOWER_OTA_STATUS_MIN FLOWER_OTA_STATUS_OTA_STARTED
#define _FLOWER_OTA_STATUS_MAX FLOWER_OTA_STATUS_OTA_FAILED
#define _FLOWER_OTA_STATUS_ARRAYSIZE ((flower_ota_status_t)(FLOWER_OTA_STATUS_OTA_FAILED+1))

#define _FLOWER_COMMAND_ROLE_MIN FLOWER_COMMAND_ROLE_COMMAND_ROLE_UNSPECIFIED
#define _FLOWER_COMMAND_ROLE_MAX FLOWER_COMMAND_ROLE_COMMAND_ROLE_AGENT
#define _FLOWER_COMMAND_ROLE_ARRAYSIZE ((flower_command_role_t)(FLOWER_COMMAND_ROLE_COMMAND_ROLE_AGENT+1))




#define flower_ota_response_t_status_ENUMTYPE flower_ota_status_t

#define flower_relay_control_resp_t_result_ENUMTYPE flower_cmd_result_t

#define flower_command_t_role_ENUMTYPE flower_command_role_t

#define flower_command_response_t_role_ENUMTYPE flower_command_role_t



/* Initializer values for message structs */
#define FLOWER_STATUS_REPORT_INIT_DEFAULT        {0, 0, false, FLOWER_DEVICE_VERSION_INIT_DEFAULT}
#define FLOWER_RELAY_CONTROL_INIT_DEFAULT        {0, 0}
#define FLOWER_OTA_COMMAND_INIT_DEFAULT          {"", false, FLOWER_DEVICE_VERSION_INIT_DEFAULT, false, FLOWER_DEVICE_VERSION_INIT_DEFAULT}
#define FLOWER_OTA_RESPONSE_INIT_DEFAULT         {_FLOWER_OTA_STATUS_MIN, 0, ""}
#define FLOWER_RELAY_CONTROL_RESP_INIT_DEFAULT   {_FLOWER_CMD_RESULT_MIN, ""}
#define FLOWER_COMMAND_INIT_DEFAULT              {_FLOWER_COMMAND_ROLE_MIN, 0, {FLOWER_RELAY_CONTROL_INIT_DEFAULT}}
#define FLOWER_COMMAND_RESPONSE_INIT_DEFAULT     {_FLOWER_COMMAND_ROLE_MIN, 0, {FLOWER_RELAY_CONTROL_RESP_INIT_DEFAULT}}
#define FLOWER_DEVICE_VERSION_INIT_DEFAULT       {0, 0, 0}
#define FLOWER_STATUS_REPORT_INIT_ZERO           {0, 0, false, FLOWER_DEVICE_VERSION_INIT_ZERO}
#define FLOWER_RELAY_CONTROL_INIT_ZERO           {0, 0}
#define FLOWER_OTA_COMMAND_INIT_ZERO             {"", false, FLOWER_DEVICE_VERSION_INIT_ZERO, false, FLOWER_DEVICE_VERSION_INIT_ZERO}
#define FLOWER_OTA_RESPONSE_INIT_ZERO            {_FLOWER_OTA_STATUS_MIN, 0, ""}
#define FLOWER_RELAY_CONTROL_RESP_INIT_ZERO      {_FLOWER_CMD_RESULT_MIN, ""}
#define FLOWER_COMMAND_INIT_ZERO                 {_FLOWER_COMMAND_ROLE_MIN, 0, {FLOWER_RELAY_CONTROL_INIT_ZERO}}
#define FLOWER_COMMAND_RESPONSE_INIT_ZERO        {_FLOWER_COMMAND_ROLE_MIN, 0, {FLOWER_RELAY_CONTROL_RESP_INIT_ZERO}}
#define FLOWER_DEVICE_VERSION_INIT_ZERO          {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define FLOWER_RELAY_CONTROL_ON_TAG              1
#define FLOWER_RELAY_CONTROL_DURATION_MS_TAG     2
#define FLOWER_OTA_RESPONSE_STATUS_TAG           1
#define FLOWER_OTA_RESPONSE_PROGRESS_TAG         2
#define FLOWER_OTA_RESPONSE_MESSAGE_TAG          3
#define FLOWER_RELAY_CONTROL_RESP_RESULT_TAG     1
#define FLOWER_RELAY_CONTROL_RESP_REASON_TAG     2
#define FLOWER_COMMAND_RESPONSE_ROLE_TAG         1
#define FLOWER_COMMAND_RESPONSE_RELAY_CONTROL_TAG 2
#define FLOWER_COMMAND_RESPONSE_OTA_TAG          3
#define FLOWER_DEVICE_VERSION_MAJOR_TAG          1
#define FLOWER_DEVICE_VERSION_MINOR_TAG          2
#define FLOWER_DEVICE_VERSION_PATCH_TAG          3
#define FLOWER_STATUS_REPORT_SIGNAL_DBM_TAG      1
#define FLOWER_STATUS_REPORT_TIMESTAMP_TAG       2
#define FLOWER_STATUS_REPORT_VERSION_TAG         3
#define FLOWER_OTA_COMMAND_URL_TAG               1
#define FLOWER_OTA_COMMAND_EXPECTED_VERSION_TAG  2
#define FLOWER_OTA_COMMAND_MINI_COMPACT_VERSION_TAG 3
#define FLOWER_COMMAND_ROLE_TAG                  1
#define FLOWER_COMMAND_RELAY_CONTROL_TAG         2
#define FLOWER_COMMAND_OTA_TAG                   3

/* Struct field encoding specification for nanopb */
#define FLOWER_STATUS_REPORT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    signal_dbm,        1) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           3)
#define FLOWER_STATUS_REPORT_CALLBACK NULL
#define FLOWER_STATUS_REPORT_DEFAULT NULL
#define flower_status_report_t_version_MSGTYPE flower_device_version_t

#define FLOWER_RELAY_CONTROL_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     on,                1) \
X(a, STATIC,   SINGULAR, UINT32,   duration_ms,       2)
#define FLOWER_RELAY_CONTROL_CALLBACK NULL
#define FLOWER_RELAY_CONTROL_DEFAULT NULL

#define FLOWER_OTA_COMMAND_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   url,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  expected_version,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mini_compact_version,   3)
#define FLOWER_OTA_COMMAND_CALLBACK NULL
#define FLOWER_OTA_COMMAND_DEFAULT NULL
#define flower_ota_command_t_expected_version_MSGTYPE flower_device_version_t
#define flower_ota_command_t_mini_compact_version_MSGTYPE flower_device_version_t

#define FLOWER_OTA_RESPONSE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1) \
X(a, STATIC,   SINGULAR, INT32,    progress,          2) \
X(a, STATIC,   SINGULAR, STRING,   message,           3)
#define FLOWER_OTA_RESPONSE_CALLBACK NULL
#define FLOWER_OTA_RESPONSE_DEFAULT NULL

#define FLOWER_RELAY_CONTROL_RESP_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    result,            1) \
X(a, STATIC,   SINGULAR, STRING,   reason,            2)
#define FLOWER_RELAY_CONTROL_RESP_CALLBACK NULL
#define FLOWER_RELAY_CONTROL_RESP_DEFAULT NULL

#define FLOWER_COMMAND_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    role,              1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,relay_control,payload.relay_control),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ota,payload.ota),   3)
#define FLOWER_COMMAND_CALLBACK NULL
#define FLOWER_COMMAND_DEFAULT NULL
#define flower_command_t_payload_relay_control_MSGTYPE flower_relay_control_t
#define flower_command_t_payload_ota_MSGTYPE flower_ota_command_t

#define FLOWER_COMMAND_RESPONSE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    role,              1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,relay_control,payload.relay_control),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ota,payload.ota),   3)
#define FLOWER_COMMAND_RESPONSE_CALLBACK NULL
#define FLOWER_COMMAND_RESPONSE_DEFAULT NULL
#define flower_command_response_t_payload_relay_control_MSGTYPE flower_relay_control_resp_t
#define flower_command_response_t_payload_ota_MSGTYPE flower_ota_response_t

#define FLOWER_DEVICE_VERSION_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    major,             1) \
X(a, STATIC,   SINGULAR, INT32,    minor,             2) \
X(a, STATIC,   SINGULAR, INT32,    patch,             3)
#define FLOWER_DEVICE_VERSION_CALLBACK NULL
#define FLOWER_DEVICE_VERSION_DEFAULT NULL

extern const pb_msgdesc_t flower_status_report_t_msg;
extern const pb_msgdesc_t flower_relay_control_t_msg;
extern const pb_msgdesc_t flower_ota_command_t_msg;
extern const pb_msgdesc_t flower_ota_response_t_msg;
extern const pb_msgdesc_t flower_relay_control_resp_t_msg;
extern const pb_msgdesc_t flower_command_t_msg;
extern const pb_msgdesc_t flower_command_response_t_msg;
extern const pb_msgdesc_t flower_device_version_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define FLOWER_STATUS_REPORT_FIELDS &flower_status_report_t_msg
#define FLOWER_RELAY_CONTROL_FIELDS &flower_relay_control_t_msg
#define FLOWER_OTA_COMMAND_FIELDS &flower_ota_command_t_msg
#define FLOWER_OTA_RESPONSE_FIELDS &flower_ota_response_t_msg
#define FLOWER_RELAY_CONTROL_RESP_FIELDS &flower_relay_control_resp_t_msg
#define FLOWER_COMMAND_FIELDS &flower_command_t_msg
#define FLOWER_COMMAND_RESPONSE_FIELDS &flower_command_response_t_msg
#define FLOWER_DEVICE_VERSION_FIELDS &flower_device_version_t_msg

/* Maximum encoded size of messages (where known) */
#define FLOWER_COMMAND_RESPONSE_SIZE             71
#define FLOWER_COMMAND_SIZE                      333
#define FLOWER_DEVICE_VERSION_SIZE               33
#define FLOWER_FLOWER_PB_H_MAX_SIZE              FLOWER_COMMAND_SIZE
#define FLOWER_OTA_COMMAND_SIZE                  328
#define FLOWER_OTA_RESPONSE_SIZE                 46
#define FLOWER_RELAY_CONTROL_RESP_SIZE           67
#define FLOWER_RELAY_CONTROL_SIZE                8
#define FLOWER_STATUS_REPORT_SIZE                57

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
